# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Test
      run: go test -v ./...

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build .
      
    - name: ls file 
      run: ls -la
      
    - name: Rename file 
      run: mv mailra mailra_linux_amd64

    - name: Build
      run: GOOS=darwin GOARCH=arm64 go build .
      
    - name: Rename file 
      run: mv mailra mailra_osx_arm64

      
    - uses: actions/upload-artifact@v4
      with:
        name: mailra_linux_amd64
        path: mailra_linux_amd64
    - uses: actions/upload-artifact@v4
      with:
        name: mailra_osx_arm64
        path: mailra_osx_arm64
